SchoolManagementSystem/Controllers/StudentReportController.cs
using SMSBusiness.Repository.Abstract;
using SMSBusiness.Repository.Concrete;
using SMSDataContract.Accounts;
using SMSDataContract.Common;
using System;
using System.Collections.Generic;
using System.Dynamic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using System.Web.Script.Serialization;
using PagedList;
using PagedList.Mvc;
using System.Text;

namespace SchoolManagementSystem.Controllers
{
    [Authorize(Roles = "Admin")]
    public class StudentReportController : Controller
    {
        IAssessmentCategories repoAssessmentCategory = new AssessmentCategoriesBLL();
        IDailyAssessmentType repoAssessmentType = new DailyAssessmentTypeBLL();
        IDailyAssessmentSubType repoAssessementSubType = new DailyAssessmentSubTypeBLL();
        IDailyAssessmentOperation repoOperation = new DailyAssessmentOperationBLL();
        IAcadmicAssessmentOperation repAcOperation = new AcadmicAssessmentOperationBLL();
        ITeacherAssessmentOperation repTAOperation = new TeacherAssessmentOperationBLL();
        // GET: /StudentReport/
        //Get Assessment Categories
        public ActionResult GetALLAssessmentCategories()
        {
            return View(repoAssessmentCategory.GetALLAssessmentCategories().ToList());
        }
        [HttpGet]
        public ActionResult AddChangesAssessmentCategory(int Id)
        {
            AssessmentCategories dAssessCategory = repoAssessmentCategory.GetAssessmentCategoryById(Id);
            if (Id == 0)
            {
                AssessmentCategories dassesscategory = new AssessmentCategories();

                return View(dassesscategory);
            }
            else
                return View(dAssessCategory);
        }
        [HttpPost]
        public ActionResult AddChangesAssessmentCategory(AssessmentCategories dAssesscategory)
        {
            var userloggedId = User.Identity.GetUserId();
            if (dAssesscategory.AssessmentCategoryId == 0)
            {
                dAssesscategory.CreatedById = userloggedId;

            }
            else
            {
                dAssesscategory.ModifiedById = userloggedId;
                dAssesscategory.ModifiedDate = DateTime.Now;
            }
            int getStatus = repoAssessmentCategory.AddChangeAssessmentCategories(dAssesscategory);
            return RedirectToAction("GetALLAssessmentCategories");
        }
        // Get Assessment Types
        public ActionResult GetALLAssessment()
        {
            return View(repoAssessmentType.GetAllAssessmentType().ToList());
        }
        [HttpGet]
        public ActionResult AddChangesAssessmentType(int Id)
        {
            DailyAssessmentType dAssessType = repoAssessmentType.GetDailyAssessmentById(Id);
            if (Id == 0)
            {
                DailyAssessmentType dassesstype = new DailyAssessmentType();

                return View(dassesstype);
            }
            else
                return View(dAssessType);
        }
        [HttpPost]
        public ActionResult AddChangesAssessmentType(DailyAssessmentType dAssesstype, int AssessmentCategoryId)
        {
            var userloggedId = User.Identity.GetUserId();
            dAssesstype.AssessmentCategoryId = AssessmentCategoryId;
            if (dAssesstype.AssessmentTypeId == 0)
            {
                dAssesstype.CreatedById = userloggedId;

            }
            else
            {
                dAssesstype.ModifiedById = userloggedId;
                dAssesstype.ModifiedDate = DateTime.Now;
            }
            int getStatus = repoAssessmentType.AddChangeDailyAssessmentType(dAssesstype);
            return RedirectToAction("GetALLAssessment");
        }
        //Get All SubAssement Type
        public ActionResult GetALLSubAssessment(int? page)
        {
            return View(repoAssessementSubType.GetAllAssessmentSubType().ToPagedList(page ?? 1, 10));
        }
        [HttpGet]
        public ActionResult AddChangesSubAssessmentType(int Id)
        {
            DailyAssessmentSubType subAssessment = repoAssessementSubType.GetDailyAssessmentSubTypeById(Id);
            if (Id == 0)
            {
                DailyAssessmentSubType subassessmen = new DailyAssessmentSubType();
                return View(subassessmen);
            }
            return View(subAssessment);
        }
        [HttpPost]
        public ActionResult AddChangesSubAssessmentType(DailyAssessmentSubType dailyAssementSubType)
        {
            var userloggedId = User.Identity.GetUserId();
            if (dailyAssementSubType.AssessmentSubTypeId == 0)
            {
                dailyAssementSubType.CreatedById = userloggedId;

            }
            else
            {
                dailyAssementSubType.ModifiedById = userloggedId;
                dailyAssementSubType.ModifiedDate = DateTime.Now;
            }
            int getStatus = repoAssessementSubType.AddChangesAssessmentSubType(dailyAssementSubType);
            return RedirectToAction("GetALLSubAssessment");
        }
        // Student General Assessment
        [HttpGet]
        public ActionResult GetALLStudentGeneralAssessment(int? AcadmicClassId, int? StudentId, DateTime? StartDate, DateTime? EndDate)
        {
            StartDate = StartDate == null ? DateTime.Now : (DateTime)StartDate;
            EndDate = EndDate == null ? DateTime.Now : (DateTime)EndDate;
            return View(repoAssessementSubType.GetStudentGeneralAssessment(AcadmicClassId, StudentId,(DateTime)StartDate,(DateTime)EndDate).ToList());
        }
        [HttpGet]
        public ActionResult AddChangesAssessmentReport(int? AcadmicClassId, int? StudentId, string CreateDate)
        {
            DailyAssessmentHelper myModel = new DailyAssessmentHelper();
            myModel.ParentAssessments = repoAssessmentType.GetALLAssignedParentAssessments();
            if (AcadmicClassId > 0)
            {
                List<DailyAssessmentSubType> GetALLSubAssessments = repoAssessementSubType.GetStudentSingleGeneralAssessment(AcadmicClassId, StudentId, CreateDate).ToList();
                if (GetALLSubAssessments[0].OperationalId > 0)
                {
                    myModel.ChildAssessments = GetALLSubAssessments;

                }
                return View(myModel);
            }
            else
            {
                myModel.ChildAssessments = repoAssessementSubType.GetAllAssessmentSubType();
                return View(myModel);
            }
        }
        [HttpPost]
        public ActionResult AddChangesAssessmentReport(DailyAssessmentHelper helper, int AcadmicClassId, int StudentId)
        {
            var userloggedId = User.Identity.GetUserId();
            for (int i = 0; i < helper.ChildAssessments.Count; i++)
            {
                DailyAssessmentOperation op = new DailyAssessmentOperation();
                op.AcadmicClassId = AcadmicClassId;
                op.StudentId = StudentId;
                op.ParentAssessmentId = helper.ChildAssessments[i].AssessmentTypeId;
                op.AssessmentSubTypeId = helper.ChildAssessments[i].AssessmentSubTypeId;
                op.AssementStatus = helper.ChildAssessments[i].SelectedEvaluation;
                op.WorseConsequence = helper.ChildAssessments[i].Concequence;
                op.AssessmentFormat = helper.ChildAssessments[i].AssessmentFormat; // Assessment format refer to consequence or non-consequence
                op.CreateDate = helper.ChildAssessments[i].CreateDate;
                op.CreatedById = helper.ChildAssessments[i].CreatedById;
                if (helper.ChildAssessments[i].OperationalId == 0)
                {
                    op.CreatedById = userloggedId;
                }
                else
                {
                    op.DailyAssessmentOpertationId = helper.ChildAssessments[i].OperationalId;
                    op.ModifiedById = userloggedId;
                    op.ModifiedDate = DateTime.Now;
                }
                int getStatus = repoOperation.AddChangesAssessmentOperation(op);
            }

            return RedirectToAction("GetALLStudentGeneralAssessment");
        }

        public ActionResult DeleteStudentGeneralAssessment(int AcadmicClassId, int StudentId, DateTime CreatedDate)
        {
            int DeleteStatus = repoAssessementSubType.DeleteStudentGeneralAssessment(AcadmicClassId, StudentId, CreatedDate);
            return RedirectToAction("GetALLStudentGeneralAssessment");
        }

        // Student Acadmic Assessment
        public ActionResult GetALLStudentAcadmicAssessment(int? AcadmicClassId, int? StudentId, int? CourseId, DateTime? StartDate, DateTime? EndDate)
        {
            StartDate = StartDate == null ? DateTime.Now : (DateTime)StartDate;
            EndDate = EndDate == null ? DateTime.Now : (DateTime)EndDate;
            return View(repoAssessementSubType.GetStudentAcadmicAssessment(AcadmicClassId, StudentId, CourseId,(DateTime) StartDate,(DateTime)EndDate).ToList());
        }

        [HttpGet]
        public ActionResult AddChangesAcadmicAssessmentReport(int? AcadmicClassId, int? StudentId, int? CourseId, string CreateDate)
        {
            DailyAssessmentHelper myModel = new DailyAssessmentHelper();
            if (AcadmicClassId > 0)
            {
                List<DailyAssessmentType> GetALLSubAssessments = repoAssessementSubType.GetStudentSingleAcadmicAssessment(AcadmicClassId, StudentId, CourseId, CreateDate).ToList();
                if (GetALLSubAssessments[0].OperationalId > 0)
                {
                    myModel.ParentAssessments = GetALLSubAssessments;
                }
                return View(myModel);
            }
            else
            {
                myModel.ParentAssessments = repoAssessmentType.GetALLAssignedParentAcadmicAssessments();
                return View(myModel);
            }
        }

        [HttpPost]

SchoolManagementSystem/Views/StudentReport/AddChangesAssessmentCategory.cshtml
@model SMSDataContract.Accounts.AssessmentCategories

@{

    Layout = null;
}


@using (Html.BeginForm("AddChangesAssessmentCategory", "StudentReport", FormMethod.Post))
{
    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">

                <div class="modal-body">
                    <div class="col-md-12 col-sm-12">
                        <div class="row well">
                            <div class="form-horizontal">
                                @if (Model.AssessmentCategoryId == 0)
                                {
                                    <span class="HeadingStyle">Add Assessment Category </span>

                                }
                                else
                                {
                                    @Html.HiddenFor(x => x.AssessmentCategoryId)
                                    @Html.HiddenFor(x => x.CreatedById)
                                    @Html.HiddenFor(x => x.CreateDate)
                                    
                                   
                                    <span class="HeadingStyle">Update Assessment Category</span>
                                }
                                <hr />

                                @Html.AntiForgeryToken()

                                <div class="form-horizontal">

                                    @Html.ValidationSummary(true)

                                    <div class="form-group">

                                        @Html.LabelFor(model => model.AssessmentName, new { @class = "control-label col-md-4" })
                                        <div id="dvCategory" style="text-align: center; margin-top: -25px; margin-left:57%;">
                                            <span id="AssessmentMsg" class="error" style="display:none;"></span>
                                        </div>
                                        <div class="col-md-5">

                                            @Html.EditorFor(model => model.AssessmentName, new { htmlAttributes = new { @class = "form-control" } })
                                            @Html.ValidationMessageFor(model => model.AssessmentName)
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="form-group">
                                            <span class="col-md-3 col-md-offset-7">

                                                <button id="btnAddEdit" type="submit" class="btn btn-primary btn-success pull-right">
                                                    @if (Model.AssessmentCategoryId == 0)
                                                    { <text>

                                                        Save
                                                    </text>
                                                    }
                                                    else
                                                    {
                                                        <text>

                                                            Update
                                                        </text>
                                                    }
                                                </button>

                                            </span>

                                            <button type="submit" id="btnClosemodel" class="btn btn-primary" data-dismiss="modal">Close</button>
                                        </div>
                                    </div>
                                </div>

                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
}

<script type="text/javascript">
    $("#btnClosemodel").click(function (e) {
        $('#myModal').modal('hide');
        // $('#modal').modal('toggle');
        $("#AddEdithtml").empty();
        $("div").removeClass("modal-backdrop fade in");
        e.preventDefault();

    });
    $("#btnAddEdit").click(function (e) {
        debugger;
        e.preventDefault();
        var getAssessment = $("#AssessmentName").val();
        if (getAssessment != "") {
            var model = { AssessmentName: $("#AssessmentName").val() };
            $.get("/StudentReport/CheckAssessmentCategoryExist", model)
              .success(function (response) {

                  if (response == "true") {
                      $("#AssessmentMsg").text("Assessment Name already Exist..");
                      $("#AssessmentMsg").show();

                  }
                  else {
                      $("#AssessmentMsg").text("");
                      $("#AssessmentMsg").hide();
                      $("form").submit();

                  }

              })
              .fail(function (e) {

                  alert("Can't Check AssessmentCategory Existance..")
              })

        }
        else {
            $("#AssessmentMsg").text("Enter Assessment Category");
            $("#AssessmentMsg").show();
        }
    });
</script>


SchoolManagementSystem/Views/StudentReport/AddChangesAssessmentType.cshtml
@model SMSDataContract.Accounts.DailyAssessmentType

@{

    Layout = null;
}


@using (Html.BeginForm("AddChangesAssessmentType", "StudentReport", FormMethod.Post))
{
    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">

                <div class="modal-body">
                    <div class="col-md-12 col-sm-12">
                        <div class="row well">
                            <div class="form-horizontal">
                                @if (Model.AssessmentTypeId == 0)
                                {
                                    <span class="HeadingStyle">Add Assessment Type </span>

                                }
                                else
                                {
                                    @Html.HiddenFor(x => x.AssessmentTypeId)
                                    @Html.HiddenFor(x => x.CreatedById)
                                    @Html.HiddenFor(x => x.CreateDate)
                                    <span class="HeadingStyle">Update Assessment Type</span>
                                }
                                <hr />

                                @Html.AntiForgeryToken()

                                <div class="form-horizontal">

                                    @Html.ValidationSummary(true)

                                    <div class="form-group">
                                        <div class="col-md-5 control-label"><label>Assessment Belong To</label> </div>
                                        <div id="dvCategory" style="text-align: center; margin-top: -25px; margin-left:57%;">
                                            <span id="CategoryMsg" class="error" style="display:none;"></span>
                                        </div>
                                        <div class="col-md-7">
                                            <div class="input-group">
                                                <span class="input-group-addon"><i class="glyphicon glyphicon-level-up"></i></span>
                                                @{Html.RenderPartial("../DropDownLists/DDLCategory");}
                                            </div>
                                        </div>
                                    </div>

                                    <div class="form-group">

                                        @Html.LabelFor(model => model.AssessmentName, new { @class = "control-label col-md-5" })
                                        <div id="dvCourse" style="text-align: center; margin-top: -25px; margin-left:57%;">
                                            <span id="RoomMsg" class="error" style="display:none;"></span>
                                        </div>
                                        <div class="col-md-5">

                                            @Html.EditorFor(model => model.AssessmentName, new { htmlAttributes = new { @class = "form-control" } })
                                            @Html.ValidationMessageFor(model => model.AssessmentName)
                                        </div>
                                    </div>
                                    <div id="criteria" class="form-group">

                                        @Html.LabelFor(model => model.AssessmentCriteria, new { @class = "control-label col-md-5" })
                                        <div id="dvCourse" style="text-align: center; margin-top: -25px; margin-left:57%;">
                                            <span id="AssessmentCriteriaMsg" class="error" style="display:none;"></span>
                                        </div>
                                        <div class="col-md-5">

                                            <span id="generalAssessment">  @Html.RadioButtonFor(model => model.AssessmentCriteria, "General") General </span>
                                            <span id="acadmicAssessment">  @Html.RadioButtonFor(model => model.AssessmentCriteria, "Acadmic") Acadmic </span>
                                            @Html.ValidationMessageFor(model => model.AssessmentCriteria)
                                        </div>
                                    </div>
                                    <div id="AssessmentFormats" class="form-group">
                                        @Html.LabelFor(model => model.AssessmentFormat, new { @class = "control-label col-md-5" })
                                        <div class="col-md-7">
                                            @Html.RadioButtonFor(x => x.AssessmentFormat, "true") Concequence
                                            @Html.RadioButtonFor(x => x.AssessmentFormat, "false") Reward
                                        </div>

                                    </div>

                                    <div class="row">
                                        <div class="form-group">
                                            <span class="col-md-3 col-md-offset-7">

                                                <button id="btnAddEdit" type="submit" class="btn btn-primary btn-success pull-right">
                                                    @if (Model.AssessmentTypeId == 0)
                                                    { <text>

                                                        Save
                                                    </text>
                                                    }
                                                    else
                                                    {
                                                        <text>

                                                            Update
                                                        </text>
                                                    }
                                                </button>

                                            </span>

                                            <button type="submit" id="btnClosemodel" class="btn btn-primary" data-dismiss="modal">Close</button>
                                        </div>
                                    </div>
                                </div>

                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
                                                    }

<script type="text/javascript">
    //Default Set Criteria Hide
    // $("#criteria").hide();
    $("#AssessmentFormats").hide();
    $("#ddlAssessmentCategory").change(function (e) {
        debugger;
        // $("#criteria").hide();
        var checkCategory = $("#ddlAssessmentCategory option:selected").val();

        if (checkCategory != '') {

            var getSelectedCategoryText = $("#ddlAssessmentCategory option:selected").text();

            if (getSelectedCategoryText == "Student" || getSelectedCategoryText == "student") {

                //$("#criteria").show();
                $("#generalAssessment").show();

            }
            if (getSelectedCategoryText == "Teacher" || getSelectedCategoryText == "teacher") {
                //$("#criteria").show();
                $("#generalAssessment").hide();
            }
        }

    });
    $("#btnClosemodel").click(function (e) {
        $('#myModal').modal('hide');
        // $('#modal').modal('toggle');
        $("#AddEdithtml").empty();
        $("div").removeClass("modal-backdrop fade in");
        e.preventDefault();

    });
    $("#acadmicAssessment").click(function () {
        //confirm default AssessmentFormat is non-concequence
        $("#AssessmentFormat").prop("checked", false);
        $("#AssessmentFormats").show();
    });
    $("#generalAssessment").click(function () {
        //confirm  AssessmentFormat is non-concequence
        $("#AssessmentFormat").prop("checked", false);
        $("#AssessmentFormats").hide();

    });
    $("#btnAddEdit").click(function (e) {
        debugger;
        e.preventDefault();
        var getAssessmentCategory = $("#ddlAssessmentCategory").val();
        if (getAssessmentCategory == '') {
            $("#CategoryMsg").text("Please Select Assessment Category");
            $("#CategoryMsg").show();
        }
        var isCriteriaVisible = $("#criteria").is(":visible");
        var isGeneralAssessmentVisible = $("#generalAssessment").is(":visible");
        var getradiobuttValue = $("input[type=radio][name=AssessmentCriteria]:checked").val();
        // if General  Assessment is Visible that means assessment is selected for Student Reports
        // in this Case Acadmic & General Reports can be created
        if (isGeneralAssessmentVisible == true) {
            debugger;
          
            if (typeof getradiobuttValue === "undefined") {

                $("#AssessmentCriteriaMsg").text("Please Select Assessment Criteria.");
                $("#AssessmentCriteriaMsg").show();
                return;
            }
            else {
                $("#AssessmentCriteriaMsg").text("");
                $("#AssessmentCriteriaMsg").hide();
            }
        }
            // if General Assessment is not Visible then Assessment is selected for Teacher
            // in this case only Acadmic Report can be Created.
        else {
            debugger;
            if( getradiobuttValue !=="Acadmic")
            {
                $("#AssessmentCriteriaMsg").text("Please Select Assessment Criteria.");
                $("#AssessmentCriteriaMsg").show();
                return;
            }
            else {
                $("#AssessmentCriteriaMsg").text("");
                $("#AssessmentCriteriaMsg").hide();
            }
        }
        var getAssessment = $("#AssessmentName").val();
        if (getAssessment != "") {
            var model = { AssessmentName: $("#AssessmentName").val(), AssessmentCategoryId: $("#ddlAssessmentCategory").val() };
            $.get("/StudentReport/CheckAssessmentTypeExist", model)
              .success(function (response) {

                  if (response == "true") {
                      $("#RoomMsg").text("Assessment Name already Exist..");
                      $("#RoomMsg").show();

                  }
                  else {
                      $("#RoomMsg").text("");
                      $("#RoomMsg").hide();
                      $("form").submit();

                  }

              })
              .fail(function (e) {

                  alert("Can't Check AssessmentType Existance..")
              })

        }
        else {
            $("#RoomMsg").text("Enter Assessment Type");
            $("#RoomMsg").show();
        }

    });
    // For Update Mode
    if ('@Model.AssessmentTypeId' > 0) {
        //$("#criteria").show();
        if('@Model.AssessmentCriteria'=="Acadmic")
        {
            $("#AssessmentFormats").show();
        }
    }

</script>


SchoolManagementSystem/Views/StudentReport/GetALLAssessment.cshtml
@using PagedList;
@using PagedList.Mvc;
@model IEnumerable<SMSDataContract.Accounts.DailyAssessmentType>

@{
    Layout = "~/Views/Shared/_ReportsLayout.cshtml";
}
<div id="AddEdithtml"></div>
<div id="content">
    <button id="AddNewbtn" class="btn btn-sm btn-success ">
        Add New Assessment
    </button>

    <div class="row">
        <div class="col-md-12 col-sm-12">
            <div class="well">
                <div class="row">
                    <span class="HeadingStyle">List of Assessments</span>
                    <table id="getTable" class="table table-bordered table-striped table-responsive table-hover">
                        <tr class="action info">
                            
                            <th>
                                @Html.DisplayNameFor(model => model.First().AssessmentName)
                            </th>
                            <th>
                                <b>Assessment Belong To</b>
                            </th>
                            <th>
                                @Html.DisplayNameFor(model=> model.First().AssessmentCriteria)
                            </th>
                            <th style="width:90px;"><b>ACTION</b></th>
                        </tr>

                        @foreach (var item in Model)
                    {
                            <tr>
                                
                                <td>
                                    @Html.DisplayFor(modelItem => item.AssessmentName)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem=>item.AssementCategory)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem =>item.AssessmentCriteria)
                                </td>

                                <td>

                                    <a href="javascript:AddEdit(@item.AssessmentTypeId)" id="btnEdit" class="btn btn-sm btn-info edit"><i class="glyphicon glyphicon-edit"></i></a>

                                </td>
                            </tr>
                    }

                    </table>

                </div>
            </div>
        </div>
    </div>
</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/bootstrap")




    <script type="text/javascript">

        $(document).ready(function () {
            $("#AddNewbtn").click(function () {
                AddEdit(0);

            });
        });
        function AddEdit(id) {
          
            var URL = "/StudentReport/AddChangesAssessmentType";
            var model = { Id: id };
            $.get(URL, model)
            .done(function (gethtml) {
                $("#AddEdithtml").html("");
                $("#AddEdithtml").html(gethtml);
                $('#myModal').modal('show');
                $("#myModel").modal({ "backdrop": "static" });

            })
            .fail(function (e1) { })
        }
    </script>
}