SchoolManagementSystem/Controllers/TeacherLogController.cs
using SMSBusiness.Repository.Abstract;
using SMSBusiness.Repository.Concrete;
using SMSDataContract.Accounts;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using SMSDataContract.Common;

namespace SchoolManagementSystem.Controllers
{
    public class TeacherLogController : Controller
    {
        ITeacherRepositry repoTeacher = new TeacherRepositry();
        ITeacherLessonPlan repoTeacherLessonPlan = new TeacherLessonBLL();
        ICourse courserepositry = new CourseBLL();
        IAcadmicClassBLL repClass = new AcadmicClassBLL();
        ITeacherAssignedCourse repoTeacherAssignCourse = new TeacherAssignCourseBLL();
        IDailyAssessmentSubType repoAssessementSubType = new DailyAssessmentSubTypeBLL();
        IDailyAssessmentType repoAssessmentType = new DailyAssessmentTypeBLL();
        IDailyAssessmentOperation repoOperation = new DailyAssessmentOperationBLL();
        IAcadmicAssessmentOperation repAcOperation = new AcadmicAssessmentOperationBLL();
        IStudentResultSheet stdResultSheetRepo = new StudentResultSheetBLL();
        ICourse courseRepo = new CourseBLL();
        IStudentAttendance stdAttendanceRepo = new StudentAttendanceBLL();
        IStudentResultSocialAndPersonalSkill socialSkillRepo = new StudentResultSocialAndPersonalSkillBLL();
        IStudentResultSocialDescription socialDescriptionRepo = new StudentResultSocialDescriptionBLL();
        IStudentResultWorkAndSkill studySkillRepo = new StudentResultWorkAndSkillBLL();
        IStudentResultStudyDescription studyDescriptionRepo = new StudentResultStudyDescriptionBLL();
        // GET: TeacherLog
        public ActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public ActionResult GetTeacherLessonPlans(int? AcadmicClassId, int? TeacherId, int? CourseId)
        {
            return View(repoTeacherLessonPlan.GetTeacherLessons(AcadmicClassId, TeacherId, CourseId));
        }
        [HttpGet]
        public ActionResult AddChangesTeacherLessonPlans(int Id)
        {
            TeacherLessonPlan tlp = new TeacherLessonPlan();
            if (Id == 0)
            {

                return View(tlp);
            }
            else
            {
                tlp = repoTeacherLessonPlan.GetTeacherLessonPlan(Id);
                return View(tlp);
            }
        }
        [HttpPost]
        public ActionResult AddChangesTeacherLessonPlans(TeacherLessonPlan lessonPlan)
        {
            var userIdentityId = User.Identity.GetUserId();
            if (lessonPlan.TeacherLessonPlanId > 0)
            {
                lessonPlan.ModifiedById = userIdentityId;
                lessonPlan.ModifiedDate = DateTime.Now;

            }
            else
            {
                lessonPlan.CreatedById = userIdentityId;
                lessonPlan.CreateDate = DateTime.Now;
            }
            int getStatus = repoTeacherLessonPlan.AddChangesLessonPlan(lessonPlan);
            return RedirectToAction("GetTeacherLessonPlans");
        }  

        // Reports
        // Student General Assessment
        [HttpGet]
        public ActionResult GetALLStudentGeneralAssessment(int? AcadmicClassId, int? StudentId, DateTime? StartDate,DateTime? EndDate)
        {
            StartDate = StartDate == null ? DateTime.Now : (DateTime)StartDate;
            EndDate = EndDate == null ? DateTime.Now : (DateTime)EndDate;
            return View(repoAssessementSubType.GetStudentGeneralAssessment(AcadmicClassId, StudentId,(DateTime)StartDate,(DateTime)EndDate).ToList());
        }
        [HttpGet]
        public ActionResult AddChangesAssessmentReport(int? AcadmicClassId, int? StudentId, string CreateDate)
        {
            DailyAssessmentHelper myModel = new DailyAssessmentHelper();
            myModel.ParentAssessments = repoAssessmentType.GetALLAssignedParentAssessments();
            if (AcadmicClassId > 0)
            {
                List<DailyAssessmentSubType> GetALLSubAssessments = repoAssessementSubType.GetStudentSingleGeneralAssessment(AcadmicClassId, StudentId, CreateDate).ToList();
                if (GetALLSubAssessments[0].OperationalId > 0)
                {
                    myModel.ChildAssessments = GetALLSubAssessments;

                }
                return View(myModel);
            }
            else
            {
                myModel.ChildAssessments = repoAssessementSubType.GetAllAssessmentSubType();
                return View(myModel);
            }
        }
        [HttpPost]
        public ActionResult AddChangesAssessmentReport(DailyAssessmentHelper helper, int AcadmicClassId, int StudentId)
        {
            var userloggedId = User.Identity.GetUserId();
            for (int i = 0; i < helper.ChildAssessments.Count; i++)
            {
                DailyAssessmentOperation op = new DailyAssessmentOperation();
                op.AcadmicClassId = AcadmicClassId;
                op.StudentId = StudentId;
                op.ParentAssessmentId = helper.ChildAssessments[i].AssessmentTypeId;
                op.AssessmentSubTypeId = helper.ChildAssessments[i].AssessmentSubTypeId;
                op.AssementStatus = helper.ChildAssessments[i].SelectedEvaluation;
                op.WorseConsequence = helper.ChildAssessments[i].Concequence;
                op.AssessmentFormat = helper.ChildAssessments[i].AssessmentFormat; // Assessment format refer to consequence or non-consequence
                op.CreateDate = helper.ChildAssessments[i].CreateDate;
                op.CreatedById = helper.ChildAssessments[i].CreatedById;
                if (helper.ChildAssessments[i].OperationalId == 0)
                {
                    op.CreatedById = userloggedId;
                }
                else
                {
                    op.DailyAssessmentOpertationId = helper.ChildAssessments[i].OperationalId;
                    op.ModifiedById = userloggedId;
                    op.ModifiedDate = DateTime.Now;
                }
                int getStatus = repoOperation.AddChangesAssessmentOperation(op);
            }

            return RedirectToAction("GetALLStudentGeneralAssessment");
        }
        public ActionResult DeleteStudentGeneralAssessment(int AcadmicClassId, int StudentId, DateTime CreateDate)
        {
            int DeleteStatus = repoAssessementSubType.DeleteStudentGeneralAssessment(AcadmicClassId, StudentId, CreateDate);
            return RedirectToAction("GetALLStudentGeneralAssessment");
        }
        // Student Acadmic Assessment
        public ActionResult GetALLStudentAcadmicAssessment(int? AcadmicClassId, int? StudentId, int? CourseId, DateTime? StartDate,DateTime? EndDate)
        {
            StartDate = StartDate == null ? DateTime.Now : (DateTime)StartDate;
            EndDate = EndDate == null ? DateTime.Now : (DateTime)EndDate;
           
            return View(repoAssessementSubType.GetStudentAcadmicAssessment(AcadmicClassId, StudentId, CourseId, (DateTime)StartDate,(DateTime)EndDate).ToList());
        }

        [HttpGet]
        public ActionResult AddChangesAcadmicAssessmentReport(int? AcadmicClassId, int? StudentId, int? CourseId, string CreateDate)
        {
            DailyAssessmentHelper myModel = new DailyAssessmentHelper();
            if (AcadmicClassId > 0)
            {
                List<DailyAssessmentType> GetALLSubAssessments = repoAssessementSubType.GetStudentSingleAcadmicAssessment(AcadmicClassId, StudentId, CourseId, CreateDate).ToList();
                if (GetALLSubAssessments[0].OperationalId > 0)
                {
                    myModel.ParentAssessments = GetALLSubAssessments;
                }
                return View(myModel);
            }
            else
            {
                myModel.ParentAssessments = repoAssessmentType.GetALLAssignedParentAcadmicAssessments();
                return View(myModel);
            }
        }

        [HttpPost]
        public ActionResult AddChangesAcadmicAssessmentReport(DailyAssessmentHelper helpers, int AcadmicClassId, int StudentId, int CourseId)
        {
            var userloggedId = User.Identity.GetUserId();
            for (int i = 0; i < helpers.ParentAssessments.Count; i++)
            {
                AcadmicAssessmentOperation op = new AcadmicAssessmentOperation();
                op.AcadmicClassId = AcadmicClassId;
                op.StudentId = StudentId;
                op.CourseId = CourseId;
                op.ParentAssessmentId = helpers.ParentAssessments[i].AssessmentTypeId;
                op.AssementStatus = helpers.ParentAssessments[i].SelectedEvaluation;
                op.AverageConsequence = helpers.ParentAssessments[i].AverageConcequence;
                op.WorseConsequence = helpers.ParentAssessments[i].Concequence;
                op.AssessmentFormat = helpers.ParentAssessments[i].AssessmentFormat; // Assessment format refer to consequence or non-consequence
                op.CreateDate = helpers.ParentAssessments[i].CreateDate;
                op.CreatedById = helpers.ParentAssessments[i].CreatedById;
                if (helpers.ParentAssessments[i].OperationalId == 0)
                {
                    op.CreatedById = userloggedId;
                }
                else
                {
                    op.AcadmicAssessmentOperationId = helpers.ParentAssessments[i].OperationalId;
                    op.ModifiedById = userloggedId;
                    op.ModifiedDate = DateTime.Now;
                }
                int getStatus = repAcOperation.AddChangesAcadmicAssessmentOperation(op);
            }

            return RedirectToAction("GetALLStudentAcadmicAssessment");
        }
        public ActionResult DeleteStudentAcadmicAssessment(int AcadmicClassId, int StudentId, int CourseId, DateTime CreateDate)
        {

SchoolManagementSystem/Views/TeacherLog/AddChangesStudentResult.cshtml
@using Microsoft.AspNet.Identity;
@model SMSDataContract.Accounts.StudentResultSheet
@{
    Layout = "~/Views/Shared/_TeacherLayout.cshtml";
}
@functions{
    public int GetCurrentLoggedTeacherId()
    {
        var context = new IdentitySample.Models.ApplicationDbContext();
        var userId = User.Identity.GetUserId();
        var CurrentUserDetail = context.Users.Where(user => user.Id == userId).ToList();
        return (int)CurrentUserDetail.SingleOrDefault().TeacherId;
    }
}

@using (Html.BeginForm())
{
    <div class="row">
        <div class="col-md-12 col-sm-12">

            @Html.AntiForgeryToken()
            <div class="form-horizontal">

                @Html.ValidationSummary(true)
                @Html.HiddenFor(x => x.StudentResultId)
                @Html.HiddenFor(x => x.CreatedDate)
                @Html.HiddenFor(x => x.CreatedById)
                @if (Model.StudentResultId == 0)
                {
                    <span class="HeadingStyle">Add Student Result</span>
                }
                else
                {
                    <span class="HeadingStyle">Update Student Result</span>
                }
                <hr />
                <div class="form-group">
                    <div class="col-md-3 control-label"><label>Paper Term</label> </div>

                    <div class="col-md-9">
                        <div class="input-group">
                            <span class="input-group-addon"><i class="glyphicon glyphicon-level-up"></i></span>

                            <div id="dvDDLPaperTerm">
                                @Html.DropDownListFor(x => x.PaperTerm, new List<SelectListItem>(){
                              new SelectListItem()    { Text = "Mid Term", Value = "MidTerm" },
                              new SelectListItem()    { Text = "Final Term", Value = "FinalTerm"}
                              }, "Select Term", new { id = "ddlTerm", @class = "form-control" })
                            </div>
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-3 control-label"><label>Acadmic Class</label> </div>
                    <div class="col-md-9">
                        <div class="input-group">
                            <span class="input-group-addon"><i class="glyphicon glyphicon-level-up"></i></span>
                            @{Html.RenderAction("DDLTeacherAssignedClass", "TeacherLog", new { @TeacherId = GetCurrentLoggedTeacherId() });}
                        </div>

                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-3 control-label"><label>Student</label> </div>

                    <div class="col-md-9">
                        <div class="input-group">
                            <span class="input-group-addon"><i class="glyphicon glyphicon-level-up"></i></span>

                            <div id="dvDDLStudent">
                              @{Html.RenderAction("DDLStudent", "TeacherLog", new { AcadmicClassId = 0 });}
                               
                            </div>
                        </div>
                    </div>
                </div>
                


                <div id="AddEditResultTemplate">
                </div>
                
                  @*<div class="form-group">
                    <div class="col-md-8">
                        @if (Model.StudentResultId == 0)
                        {
                            <div>
                                <input type="submit" value="Add" style="background-color:#fab625;color:white;" class="btn pull-right" />
                            </div>
                        }
                        else
                        {
                            <div>
                                <input type="submit" value="Update" style="background-color:#fab625;color:white;" class="btn pull-right" />
                            </div>
                        }
                    </div>
                </div>*@

            </div>

        </div>
    </div>

}

@section Scripts {
   
    <script type="text/javascript">
        {
            $(document).ready(function () {
                $("#ddlAcadmicClass").change(function () {
                   
                    var getClass = $("#ddlAcadmicClass :selected").val();
                    if (getClass != '') {
                        LoadDDLStudent();
                       
                        
                    }
                    else {
                        $("#AcadmicclassMsg").show();
                        $("#AcadmicclassMsg").text("Please Select Class");
                    }


                });
                //change event of ddlStudent
                $('body').on("change", "#ddlStudent", function () {
                    var getClass = $("#ddlAcadmicClass :selected").val();
                    var getStudent = $("#ddlStudent :selected").val();
                    var Term = $("#ddlTerm :selected").val();
                    if (getStudent != '' && Term !='') {
                        GetResultTemplate(getClass, getStudent, Term);
                    }
                    else {
                     
                    }
                });
                
            });
            function LoadDDLStudent() {
               
                var ClassId = $("#ddlAcadmicClass :selected").val();
                var model = { AcadmicClassId: ClassId };
                var Url = null;
                Url = "/TeacherLog/DDLStudent";
                 // Fill Student Dropdown
                $.get(Url, model)
                .done(function (stdhtml) {
                    $("#dvDDLStudent").html(stdhtml);
                    if ('@Model.StudentId' > 0) {
                        $('#ddlStudent option[value="@Model.StudentId"]').attr("selected", true);
                    }
                    else { $('#ddlStudent option[value=""]').attr("selected", true); }
                })
                           .fail(function (ex1, ex2) {
                               alert("Can't get Student DDL");
                           });
                        
            }

            function GetResultTemplate(ClassId,StudentId,Term)
            { 
                var model = { AcadmicClassId: ClassId, StudentId: StudentId,PaperTerm:Term };
                $.get("/TeacherLog/ResultTemplate", model)
                .done(function (html) {
                    $("#AddEditResultTemplate").empty().html();
                    $("#AddEditResultTemplate").append(html);
                    if ($("#AddEditResultTemplate").has("#ResultSheet").length==0)
                    {
                        $("#AddEditResultTemplate").append("<div>No Record Found For Selected Student.</div>");
                    }
                })
                .fail(function (e1) {
                    alert("fail to get Result Template");
                })


            }
            

        }


    </script>
}









SchoolManagementSystem/Views/TeacherLog/AddChangesTeacherLessonPlans.cshtml
@using Microsoft.AspNet.Identity;
@model SMSDataContract.Accounts.TeacherLessonPlan
@{
    Layout = "~/Views/Shared/_TeacherLayout.cshtml";
}
@functions{
    public int GetCurrentLoggedTeacherId()
    {
        var context = new IdentitySample.Models.ApplicationDbContext();
        var userId = User.Identity.GetUserId();
        var CurrentUserDetail = context.Users.Where(user => user.Id == userId).ToList();
        return (int)CurrentUserDetail.SingleOrDefault().TeacherId;
    }
}
<div id="Loading" class="modal-sm">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Loading.....</h4>
            </div>
            <div class="modal-body">
                <div class="progress progress-bar-striped action">
                    <div class="progress-bar" style="width:100%;"></div>
                </div>
            </div>
        </div>
    </div>
</div>
@using (Html.BeginForm())
{
    <div class="row">
        <div class="col-md-12 col-sm-12">

            @Html.AntiForgeryToken()
            <div class="form-horizontal">

                @Html.ValidationSummary(true)
                @Html.HiddenFor(x=>x.TeacherLessonPlanId)
                @Html.HiddenFor(x => x.CreateDate)
                @Html.HiddenFor(x => x.CreatedById)
                @if (Model.TeacherLessonPlanId == 0)
                {
                    <span class="HeadingStyle">Add Teacher Lesson Plan</span>
                }
                else
                {
                    <span class="HeadingStyle">Update Teacher Lesson Plan</span>
                }
                <hr />
                <div class="form-group">
                    <div class="col-md-3 control-label"><label>Acadmic Class</label> </div>
                    <div class="col-md-9">
                        <div class="input-group">
                            <span class="input-group-addon"><i class="glyphicon glyphicon-level-up"></i></span>
                            @if(Model.TeacherId>0)
                            {Html.RenderAction("DDLTeacherAssignedClass", "TeacherLog", new { @TeacherId = Model.TeacherId });}
                            else
                            {Html.RenderAction("DDLTeacherAssignedClass", "TeacherLog", new { @TeacherId = GetCurrentLoggedTeacherId() });}

                        </div>

                    </div>
                </div>
                <input type="hidden" name="TeacherId" value="@GetCurrentLoggedTeacherId()"/>
                <div class="form-group">
                    <div class="col-md-3 control-label"><label>Course</label> </div>

                    <div class="col-md-9">
                        <div class="input-group">
                            <span class="input-group-addon"><i class="glyphicon glyphicon-level-up"></i></span>
                            <div id="dvDDLCourse">
                                @if(Model.CourseId>0)
                                {Html.RenderAction("DDLTeacherAssignedCourse", "TeacherLog", new { @TeacherId = Model.TeacherId, @AcadmicClassId = Model.AcadmicClassId });}
                                else
                                { Html.RenderAction("DDLTeacherAssignedCourse", "TeacherLog", new { @TeacherId = 0, @AcadmicClassId = 0 }); }
                                @Html.ValidationMessageFor(model => model.CourseId, "", new { @class = "text-danger" })
                            </div>

                        </div>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-3 control-label"><label>Lesson</label> </div>

                    <div class="col-md-9">
                        <div class="input-group">
                            <span class="input-group-addon"><i class="glyphicon glyphicon-level-up"></i></span>
                            @Html.EditorFor(model => model.Lesson, new { htmlAttributes = new { @class = "form-control" } })

                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-3 control-label"><label>Topic</label> </div>

                    <div class="col-md-9">
                        <div class="input-group">
                            <span class="input-group-addon"><i class="glyphicon glyphicon-level-up"></i></span>
                            @Html.EditorFor(model => model.Topic, new { htmlAttributes = new { @class = "form-control" } })

                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-3 control-label"><label>Sub Topic</label> </div>

                    <div class="col-md-9">
                        <div class="input-group">
                            <span class="input-group-addon"><i class="glyphicon glyphicon-level-up"></i></span>
                            @Html.EditorFor(model => model.SubTopic, new { htmlAttributes = new { @class = "form-control" } })

                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-3 control-label"><label>Objective</label> </div>

                    <div class="col-md-9">
                        <div class="input-group">
                            <span class="input-group-addon"><i class="glyphicon glyphicon-level-up"></i></span>
                            @Html.EditorFor(model => model.Objective, new { htmlAttributes = new { @class = "form-control" } })

                        </div>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-3 control-label"><label>OutComes</label> </div>

                    <div class="col-md-9">
                        <div class="input-group">
                            <span class="input-group-addon"><i class="glyphicon glyphicon-level-up"></i></span>
                            @Html.EditorFor(model => model.OutComes, new { htmlAttributes = new { @class = "form-control" } })

                        </div>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-3 control-label"><label>Teaching Methodology</label> </div>

                    <div class="col-md-9">
                        <div class="input-group">
                            <span class="input-group-addon"><i class="glyphicon glyphicon-level-up"></i></span>
                            @Html.EditorFor(model => model.TeachingMethodology, new { htmlAttributes = new { @class = "form-control" } })

                        </div>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-3 control-label"><label>Resource Required</label> </div>

                    <div class="col-md-9">
                        <div class="input-group">
                            <span class="input-group-addon"><i class="glyphicon glyphicon-level-up"></i></span>
                            @Html.EditorFor(model => model.ResourceRequired, new { htmlAttributes = new { @class = "form-control" } })

                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-3 control-label"><label>Activity</label> </div>

                    <div class="col-md-9">
                        <div class="input-group">
                            <span class="input-group-addon"><i class="glyphicon glyphicon-level-up"></i></span>
                            @Html.EditorFor(model => model.Activity, new { htmlAttributes = new { @class = "form-control" } })

                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-8">
                        
                            <div>
                                <input type="submit" id="btnAddUpdate" value="@(Model.TeacherLessonPlanId==0?"Add":"Update")" style="background-color:#fab625;color:white;" class="btn pull-right" />
                            </div>
                        
                        
                    </div>
                </div>

            </div>

        </div>
    </div>

                                    }

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/bootstrap")
    <script type="text/javascript">
        {

            $(document).ready(function () {
                $("#Loading").hide();
                if('@Model.AcadmicClassId'>0)
                {
                    $('#ddlAcadmicClass option[value="@Model.AcadmicClassId"]').prop("selected", true);
                    $('#ddlCourse option[value="@Model.CourseId"]').prop("selected", true);
                }


                // change event of ddlAcadmicClass
                $("#ddlAcadmicClass").change(function () {
                    var getClass = $("#ddlAcadmicClass :selected").val();
                    if (getClass != '') {
                        $(this).removeAttr("style");
                        $("#Loading").show();
                        LoadCourse();
                        $("#Loading").hide();

                    }
                    else {
                        $("#ddlAcadmicClass").css("border", "1px solid red");
                    }


                });
                //change event of ddlCourse
                $('body').on("change", "#ddlCourse", function () {
                    var getCourse = $("#ddlCourse :selected").val();
                    if (getCourse != '') {
                        $(this).removeAttr("style");
                    }
                    else {
                        $("#ddlCourse").css("border", "1px solid red");
                    }

                });
               
                // Add btn Click Event
                $("#btnAddUpdate").click(function (e) {
                    e.preventDefault();
                    var getClass = $("#ddlAcadmicClass :selected").val();
                    var getCourse = $("#ddlCourse :selected").val();
                    if (getClass == '') {
                        $("#ddlAcadmicClass").css("border", "1px solid red");
                        return false;
                    }
                    else if (getCourse == '') {
                        $("#ddlCourse").css("border", "1px solid red");
                        return false;
                    }
                    else {
                        $("form").submit();
                    }
                });

            });
            function LoadCourse() {
                var ClassId = $("#ddlAcadmicClass :selected").val();
                var Teacherid = '@GetCurrentLoggedTeacherId()';
                var model = { TeacherId: Teacherid, AcadmicClassId: ClassId };
                var Url = null;
                var Url = "/TeacherLog/DDLTeacherAssignedCourse";
                $.get(Url, model)
                        .done(function (siteHtml) {
                            $("#dvDDLCourse").html(siteHtml);
                        })
                    .fail(function (ex1, ex2, ex3) {
                        alert("Can't get Course DDL");
                        $("#loader").hide();
                    });
            }


        }


    </script>
}



