SchoolManagementSystem/Controllers/StudentResultController.cs
using SMSBusiness.Repository.Abstract;
using SMSBusiness.Repository.Concrete;
using SMSDataContract.Accounts;
using SMSDataContract.Common;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;
using PagedList.Mvc;
using Microsoft.AspNet.Identity;
using System.Web.Script.Serialization;

namespace SchoolManagementSystem.Controllers
{

    [Authorize(Roles = "Admin")]
    public class StudentResultController : Controller
    {
        IStudentResultSheet stdResultSheetRepo = new StudentResultSheetBLL();
        IStudentResultSocialDescription socialDescriptionRepo = new StudentResultSocialDescriptionBLL();
        IStudentResultStudyDescription studyDescriptionRepo = new StudentResultStudyDescriptionBLL();
        IStudentResultSocialAndPersonalSkill socialSkillRepo = new StudentResultSocialAndPersonalSkillBLL();
        IStudentResultWorkAndSkill studySkillRepo = new StudentResultWorkAndSkillBLL();
        IStudentAttendance stdAttendanceRepo = new StudentAttendanceBLL();
        ICourse courseRepo = new CourseBLL();


        public ActionResult Index()
        {
            return View();
        }

        public ActionResult AddChangesStudentResult()
        {
            StudentResultSheet srs = new StudentResultSheet();

            return View(srs);
        }
        [HttpGet]
        public ActionResult ResultTemplate(int AcadmicClassId, int StudentId, string PaperTerm)
        {
            var ResultQuery = (from x in stdResultSheetRepo.GetStudentResultSheet().ToList()
                               where x.AcadmicClassId == AcadmicClassId && x.StudentId == StudentId
                               && x.PaperTerm == PaperTerm
                               select x).ToList();
            if (ResultQuery.Count > 0)
            {
                var ResultSheetCourse = (from x in courseRepo.GetALLCourse().ToList()
                                         join y in ResultQuery.ToList() on x.CourseId equals y.CourseId
                                         select new StudentAssignedCourse() { CourseId = x.CourseId, CourseName = x.CourseName, AcadmicClassId = y.AcadmicClassId, StudentId = y.StudentId })
                                         .ToList();
                var StudentAttendance = (from x in stdAttendanceRepo.GetStudentAttendanceSheet().ToList()
                                         where x.AcadmicClassId == AcadmicClassId && x.StudentId == StudentId
                                         && x.PaperTerm == PaperTerm
                                         select x
                                            ).ToList();
                var StdSocialskill = (from x in socialSkillRepo.GetStudentSocialAndPersonalSkill().ToList()
                                      join y in socialDescriptionRepo.GetALLSocailDescriptions().ToList() on x.SocialDescriptionId equals y.SocialDescriptionId
                                      where x.AcadmicClassId == AcadmicClassId && x.StudentId == StudentId
                                      && x.TermType == PaperTerm
                                      select new StudentResultSocialAndPersonalSkill()
                                      {
                                          SocialSkillId = x.SocialSkillId,
                                          TermType = x.TermType,
                                          AcadmicClassId = x.AcadmicClassId,
                                          StudentId = x.StudentId,
                                          SocialDescriptionId = x.SocialDescriptionId,
                                          Description = y.Description,
                                          Grad = x.Grad,
                                          CreatedById = x.CreatedById,
                                          CreatedDate = x.CreatedDate,
                                          ModifiedById = x.ModifiedById,
                                          ModifiedDate = x.ModifiedDate
                                      }
                                         ).ToList();

                var stdWorkskill = (from x in studySkillRepo.GetStudentWorkAndStudySkill().ToList()
                                    join y in studyDescriptionRepo.GetALLStudyDescriptions().ToList() on x.StudyDescriptionId equals y.StudyDescriptionId
                                    where x.AcadmicClassId == AcadmicClassId && x.StudentId == StudentId
                                    && x.TermType == PaperTerm
                                    select new StudentResultWorkAndStudySkill()
                                    {
                                        WorkSkillId = x.WorkSkillId,
                                        TermType = x.TermType,
                                        AcadmicClassId = x.AcadmicClassId,
                                        StudentId = x.StudentId,
                                        StudyDescriptionId = x.StudyDescriptionId,
                                        Description = y.Description,
                                        Grade = x.Grade,
                                        CreatedById = x.CreatedById,
                                        CreatedDate = x.CreatedDate,
                                        ModifiedById = x.ModifiedById,
                                        ModifiedDate = x.ModifiedDate
                                    }

                                    ).ToList();
                ResultSheetHelper rsh = new ResultSheetHelper();
                rsh.AssignedCourses = ResultSheetCourse;
                rsh.StudentResultSheet = ResultQuery;
                rsh.StudentAttendance = StudentAttendance.FirstOrDefault();
                rsh.SrSocialAndPersonalSkill = StdSocialskill;
                rsh.SrWorkAndStudySkill = stdWorkskill;
                return View(rsh);
            }
            else
            {
                IStudentAssignCourse saC = new StudentAssignCourseBLL();
                var query = (from x in saC.GetStudentAssignedCourse().ToList()
                             where x.AcadmicClassId == AcadmicClassId
                             && x.StudentId == StudentId
                             select new StudentAssignedCourse() { CourseId = x.CourseId, CourseName = x.CourseName, AcadmicClassId = x.AcadmicClassId, StudentId = x.StudentId }).ToList();
               
                var SocailSkills = (from x in socialDescriptionRepo.GetALLSocailDescriptions().ToList()
                                    select new StudentResultSocialAndPersonalSkill() { SocialDescriptionId = x.SocialDescriptionId, Description = x.Description }
                                       ).ToList();

                var StudySkills = (from x in studyDescriptionRepo.GetALLStudyDescriptions().ToList()
                                   select new StudentResultWorkAndStudySkill() { StudyDescriptionId = x.StudyDescriptionId, Description = x.Description }).ToList();

                ResultSheetHelper rsh = new ResultSheetHelper();
                rsh.AssignedCourses = query.ToList();
                for (int i = 0; i < query.Count; i++)
                {
                    StudentResultSheet srsheet = new StudentResultSheet();
                    rsh.StudentResultSheet.Add(srsheet);
                }
                rsh.SrSocialAndPersonalSkill = SocailSkills;
                rsh.SrWorkAndStudySkill = StudySkills;
                rsh.StudentAttendance.StudentId = StudentId;
                rsh.StudentAttendance.AcadmicClassId = AcadmicClassId;
                rsh.PaperTerm = PaperTerm;
                return View(rsh);
            }
        }
        [HttpPost]
        public ActionResult ResultTemplate(ResultSheetHelper rsHelper)
        {
            var loggedUser = User.Identity.GetUserId();
            // Add Subjects result Record..
            for (int i = 0; i < rsHelper.AssignedCourses.Count; i++)
            {
                if (rsHelper.StudentResultSheet[i].StudentResultId == 0)
                {
                    StudentResultSheet srs = new StudentResultSheet()
                        {

                            StudentId = rsHelper.AssignedCourses[i].StudentId,
                            AcadmicClassId = rsHelper.AssignedCourses[i].AcadmicClassId,
                            CourseId = rsHelper.AssignedCourses[i].CourseId,
                            ClassAssessmentPercentage = rsHelper.StudentResultSheet[i].ClassAssessmentPercentage,
                            PaperPercentage = rsHelper.StudentResultSheet[i].PaperPercentage,
                            Grade = rsHelper.StudentResultSheet[i].Grade,
                            Remarks = rsHelper.StudentResultSheet[i].Remarks,
                            CreatedById = loggedUser,
                            CreatedDate = DateTime.Now,
                            PaperTerm = rsHelper.PaperTerm
                        };
                    int getStatus = stdResultSheetRepo.AddChangesStudentResultSheet(srs);
                }

            }
            // Add Student Attnedance
            StudentAttendance stdAttendance = new StudentAttendance();
            if (rsHelper.StudentAttendance.StudentAttendanceId == 0)
            {
                stdAttendance.PaperTerm = rsHelper.PaperTerm;
                stdAttendance.AcadmicClassId = rsHelper.StudentAttendance.AcadmicClassId;
                stdAttendance.StudentId = rsHelper.StudentAttendance.StudentId;
                stdAttendance.WorkingDays = rsHelper.StudentAttendance.WorkingDays;
                stdAttendance.Leaves = rsHelper.StudentAttendance.Leaves;
                stdAttendance.Absents = rsHelper.StudentAttendance.Absents;

SchoolManagementSystem/Views/StudentResult/AddChangesSocailDescriptions.cshtml
@model SMSDataContract.Accounts.StudentResultSocialDescription

@{

    Layout = null;
}


@using (Html.BeginForm("AddChangesSocailDescriptions", "StudentResult", FormMethod.Post))
{
    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">

                <div class="modal-body">
                    <div class="col-md-12 col-sm-12">
                        <div class="row well">
                            <div class="form-horizontal">
                                @Html.HiddenFor(x => x.SocialDescriptionId)
                                @Html.HiddenFor(x => x.CreatedDate)
                                @Html.HiddenFor(x => x.CreatedById)
                                @if (Model.SocialDescriptionId == 0)
                                {
                                    <span class="HeadingStyle">Add Social Description </span>

                                }
                                else
                                {
                                 
                                    <span class="HeadingStyle">Update Social Description</span>
                                }
                                <hr />
                                @using (Html.BeginForm())
                                {
                                    @Html.AntiForgeryToken()

                                    <div class="form-horizontal">

                                        @Html.ValidationSummary(true)

                                        <div class="form-group">

                                            @Html.LabelFor(model => model.Description, new { @class = "control-label col-md-3" })
                                            <div id="dvCourse" style="text-align: center; margin-top: -30px; margin-left:50%;">
                                                <span id="DescriptionMsg" class="error" style="display:none;"></span>
                                            </div>
                                            <div class="col-md-7">

                                                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                                                @Html.ValidationMessageFor(model => model.Description)
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="form-group">
                                                <span class="col-md-3 col-md-offset-7">

                                                    <button id="btnAddEdit" type="submit" class="btn btn-primary btn-success pull-right">
                                                        @if (Model.SocialDescriptionId == 0)
                                                        { <text>
                                                            Save
                                                        </text>
                                                        }
                                                        else
                                                        {
                                                            <text>

                                                                Update
                                                            </text>
                                                        }
                                                    </button>

                                                </span>


                                                <button type="submit" id="btnClosemodel" class="btn btn-primary">Close</button>
                                            </div>
                                        </div>
                                    </div>
                                }
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
}
<script type="text/javascript">
    $("#btnClosemodel").click(function (e) {
        $('#myModal').modal('hide');
        // $('#modal').modal('toggle');
        $("#AddEdithtml").empty();
        $("div").removeClass("modal-backdrop fade in");
        e.preventDefault();

    });
    $("#btnAddEdit").click(function (e) {
        e.preventDefault();
        var name = $("#Description").val();
        if (name != "") {
            var model = { Description: $("#Description").val() };
            $.get("/StudentResult/CheckSocailDescriptionsExist", model)
       .success(function (response) {

           if (response == "true") {
               $("#DescriptionMsg").text("Description Name already Exist..");
               $("#DescriptionMsg").show();

           }
           else {
               $("#DescriptionMsg").text("");
               $("#DescriptionMsg").hide();
               $("form").submit();

           }

       })
       .fail(function (e) {

           alert("Can't Check Description Existance..")
       })

        }
        else {
            $("#DescriptionMsg").text("Enter Description Name");
            $("#DescriptionMsg").show();
        }
    });
</script>







SchoolManagementSystem/Views/StudentResult/AddChangesStudyDescriptions.cshtml
@model SMSDataContract.Accounts.StudentResultStudyDescription

@{

    Layout = null;
}


@using (Html.BeginForm("AddChangesStudyDescriptions", "StudentResult", FormMethod.Post))
{
    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">

                <div class="modal-body">
                    <div class="col-md-12 col-sm-12">
                        <div class="row well">
                            <div class="form-horizontal">
                                @Html.HiddenFor(x => x.StudyDescriptionId)
                                @Html.HiddenFor(x => x.CreatedDate)
                                @Html.HiddenFor(x => x.CreatedById)
                                @if (Model.StudyDescriptionId == 0)
                                {
                                    <span class="HeadingStyle">Add Study Description </span>

                                }
                                else
                                {

                                    <span class="HeadingStyle">Update Study Description</span>
                                }
                                <hr />
                                @using (Html.BeginForm())
                                {
                                    @Html.AntiForgeryToken()

                                    <div class="form-horizontal">

                                        @Html.ValidationSummary(true)

                                        <div class="form-group">

                                            @Html.LabelFor(model => model.Description, new { @class = "control-label col-md-3" })
                                            <div id="dvCourse" style="text-align: center; margin-top: -30px; margin-left:52%;">
                                                <span id="DescriptionMsg" class="error" style="display:none;"></span>
                                            </div>
                                            <div class="col-md-7">

                                                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                                                @Html.ValidationMessageFor(model => model.Description)
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="form-group">
                                                <span class="col-md-3 col-md-offset-7">

                                                    <button id="btnAddEdit" type="submit" class="btn btn-primary btn-success pull-right">
                                                        @if (Model.StudyDescriptionId == 0)
                                                        { <text>
                                                            Save
                                                        </text>
                                                        }
                                                        else
                                                        {
                                                            <text>

                                                                Update
                                                            </text>
                                                        }
                                                    </button>

                                                </span>


                                                <button type="submit" id="btnClosemodel" class="btn btn-primary">Close</button>
                                            </div>
                                        </div>
                                    </div>
                                }
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
}
<script type="text/javascript">
    $("#btnClosemodel").click(function (e) {
        $('#myModal').modal('hide');
        // $('#modal').modal('toggle');
        $("#AddEdithtml").empty();
        $("div").removeClass("modal-backdrop fade in");
        e.preventDefault();

    });
    $("#btnAddEdit").click(function (e) {
        e.preventDefault();
        var name = $("#Description").val();
        if (name != "") {
            var model = { Description: $("#Description").val() };
            $.get("/StudentResult/CheckStudyDescriptionsExist", model)
       .success(function (response) {

           if (response == "true") {
               $("#DescriptionMsg").text("Description Name already Exist..");
               $("#DescriptionMsg").show();

           }
           else {
               $("#DescriptionMsg").text("");
               $("#DescriptionMsg").hide();
               $("form").submit();

           }

       })
       .fail(function (e) {

           alert("Can't Check Description Existance..")
       })

        }
        else {
            $("#DescriptionMsg").text("Enter Description Name");
            $("#DescriptionMsg").show();
        }
    });
</script>









SchoolManagementSystem/Views/StudentResult/ResultTemplate.cshtml
@model SMSDataContract.Common.ResultSheetHelper
@{
    Layout = null;
}
@if (Model.AssignedCourses.Count > 0)
{
    <text>
        @using (@Html.BeginForm("ResultTemplate", "StudentResult", FormMethod.Post))
        {
            <div style="width:100%;">
                @Html.HiddenFor(x => x.PaperTerm)
                <table id="ResultSheet" class="table table-bordered table-striped table-responsive table-hover">
                    <tr class="action info">
                        <th>Subject</th>
                        <th width="200px;">Class Assessment 40 %</th>
                        <th>Paper 60 %</th>
                        <th width="200px">Grade</th>
                        <th>Remark</th>

                    </tr>
                    @for (int i = 0; i < Model.AssignedCourses.Count; i++)
                    {
                        <tr>
                            @Html.HiddenFor(x => x.AssignedCourses[i].AcadmicClassId)
                            @Html.HiddenFor(x => x.AssignedCourses[i].StudentId)
                            @Html.HiddenFor(x => x.AssignedCourses[i].CourseId)
                            @Html.HiddenFor(x => x.AssignedCourses[i].CourseName)
                            <td>
                                @Html.DisplayFor(x => x.AssignedCourses[i].CourseName)
                            </td>
                            <td>@Html.TextBoxFor(x => x.StudentResultSheet[i].ClassAssessmentPercentage, new { @class = "form-control numbersOnly", @Id = "txtClassAssessmentPercentage" + i })</td>
                            <td>
                                @Html.HiddenFor(x => x.StudentResultSheet[i].CreatedById)
                                @Html.HiddenFor(x => x.StudentResultSheet[i].CreatedDate)
                                @Html.HiddenFor(x => x.StudentResultSheet[i].StudentResultId)

                                @Html.TextBoxFor(x => x.StudentResultSheet[i].PaperPercentage, new { @class = "form-control numbersOnly", @Id = "txtPaperPercentage" + i })
                            </td>
                            <td>
                                @Html.DropDownListFor(x => x.StudentResultSheet[i].Grade,
                                   new List<SelectListItem>()
                                        {
                                            
                                            new SelectListItem(){ Text= "A", Value = "A", Selected="A"== Model.StudentResultSheet[i].Grade },
                                            new SelectListItem(){ Text= "B", Value = "B" , Selected="B"== Model.StudentResultSheet[i].Grade},
                                            new SelectListItem(){ Text= "C", Value = "C",Selected="C"== Model.StudentResultSheet[i].Grade},
                                            new SelectListItem(){ Text= "D", Value = "D",Selected="D"== Model.StudentResultSheet[i].Grade},
                                            new SelectListItem(){ Text= "F", Value = "F",Selected="F"== Model.StudentResultSheet[i].Grade}
                                        }
                                  , "Select Grade", new { id = "ddlGrade", @class = "form-control" })
                            </td>
                            <td>@Html.TextBoxFor(x => x.StudentResultSheet[i].Remarks, new { @class = "form-control", @Id = "txtRemarks" + i })</td>

                        </tr>
                    }
                </table>
                <span class="subheader">Attendance</span>
                <table id="StdAttendance" class="table table-bordered table-striped table-responsive table-hover">
                    <tr class="action info">
                        <th>Working Day</th>
                        <th>Leaves</th>
                        <th>Absents</th>
                        <th>Percentage</th>

                    </tr>
                    <tr>
                        <td>
                            @Html.HiddenFor(x=>x.StudentAttendance.AcadmicClassId)
                            @Html.HiddenFor(x=>x.StudentAttendance.StudentId)
                            @Html.HiddenFor(x=>x.StudentAttendance.StudentAttendanceId)
                            @Html.TextBoxFor(x => x.StudentAttendance.WorkingDays, new { @class = "form-control numbersOnly Getpercentage" })
                        </td>
                        <td>@Html.TextBoxFor(x => x.StudentAttendance.Leaves, new { @class = "form-control numbersOnly Getpercentage" })</td>
                        <td>@Html.TextBoxFor(x => x.StudentAttendance.Absents, new { @class = "form-control numbersOnly Getpercentage" })</td>
                        <td>@Html.TextBoxFor(x => x.StudentAttendance.TotalPercentage, new { @class = "form-control numbersOnly", @readOnly="readOnly" })</td>

                    </tr>
                </table>
                <span class="subheader">Social And Personal Devlopement</span>
                <table id="stdSocialActivity" class="table table-bordered table-striped table-responsive table-hover">
                    <tr class="action info">
                        <th>Description</th>
                        <th>Grade</th>
                    </tr>
                    @for (int k = 0; k < Model.SrSocialAndPersonalSkill.Count; k++)
                    {
                        <text>
                            <tr>
                                <td>
                                    @Html.HiddenFor(x => x.SrSocialAndPersonalSkill[k].SocialSkillId)
                                    @Html.HiddenFor(x => x.SrSocialAndPersonalSkill[k].SocialDescriptionId)
                                    @Html.HiddenFor(x => x.SrSocialAndPersonalSkill[k].CreatedById)
                                    @Html.HiddenFor(x => x.SrSocialAndPersonalSkill[k].CreatedDate)
                                    @Html.DisplayFor(x => x.SrSocialAndPersonalSkill[k].Description)
                                </td>
                                <td>

                                    @Html.DropDownListFor(x => x.SrSocialAndPersonalSkill[k].Grad, new List<SelectListItem>()
                                        {
                                            
                                            new SelectListItem(){ Text= "A", Value = "A", Selected='A'== Model.SrSocialAndPersonalSkill[k].Grad },
                                            new SelectListItem(){ Text= "B", Value = "B" , Selected='B'== Model.SrSocialAndPersonalSkill[k].Grad},
                                            new SelectListItem(){ Text= "C", Value = "C",Selected='C'== Model.SrSocialAndPersonalSkill[k].Grad},
                                            new SelectListItem(){ Text= "D", Value = "D",Selected='D'== Model.SrSocialAndPersonalSkill[k].Grad},
                                            new SelectListItem(){ Text= "F", Value = "F",Selected='F'== Model.SrSocialAndPersonalSkill[k].Grad}


                                        }, "Select Grade", new { id = "ddlGrade", @class = "form-control" })
                                </td>
                            </tr>
                        </text>
                    }
                </table>
                <span class="subheader">Work And Study Devlopement</span>
                <table id="stdSocialActivity" class="table table-bordered table-striped table-responsive table-hover">
                    <tr class="action info">
                        <th>Description</th>
                        <th>Grade</th>
                    </tr>
                    @for (int j = 0; j < Model.SrWorkAndStudySkill.Count; j++)
                    {
                        <text>
                            <tr>
                                <td>
                                    @Html.HiddenFor(x => x.SrWorkAndStudySkill[j].WorkSkillId)
                                    @Html.HiddenFor(x => x.SrWorkAndStudySkill[j].CreatedById)
                                    @Html.HiddenFor(x => x.SrWorkAndStudySkill[j].CreatedDate)
                                    @Html.HiddenFor(x => x.SrWorkAndStudySkill[j].StudyDescriptionId)
                                    @Html.DisplayFor(x => x.SrWorkAndStudySkill[j].Description)
                                </td>
                                <td>
                                    @Html.DropDownListFor(x => x.SrWorkAndStudySkill[j].Grade, new List<SelectListItem>()
                                        {
                                            
                                            new SelectListItem(){ Text= "A", Value = "A",Selected='A'== Model.SrWorkAndStudySkill[j].Grade },
                                            new SelectListItem(){ Text= "B", Value = "B",Selected='B'== Model.SrWorkAndStudySkill[j].Grade},
                                            new SelectListItem(){ Text= "C", Value = "C",Selected='C'== Model.SrWorkAndStudySkill[j].Grade},
                                            new SelectListItem(){ Text= "D", Value = "D",Selected='D'== Model.SrWorkAndStudySkill[j].Grade},
                                            new SelectListItem(){ Text= "F", Value = "F",Selected='F'== Model.SrWorkAndStudySkill[j].Grade}


                                        }, "Select Grade", new { id = "ddlGrade", @class = "form-control" })
                                </td>
                            </tr>
                        </text>
                    }
                </table>

            </div>
            <div class="col-md-offset-10 col-md-12">
                <input type="submit" value="Save" class="btn btn-primary" />

            </div>
        }
    </text>
}
<script type="text/javascript">
    $(".Getpercentage").change(function () {
        
        var workingDays = parseInt( $("#StudentAttendance_WorkingDays").val());
        var absents = parseInt($("#StudentAttendance_Absents").val());
        var leaves = parseInt($("#StudentAttendance_Leaves").val());
        // since working days always greater than absents
        if (workingDays >=  absents) {
            var presentDays = workingDays - absents - leaves;
            var totalPercentage = (presentDays / workingDays) * 100;
            $("#StudentAttendance_TotalPercentage").val(totalPercentage);
        }
        else {
            alert("Working Days Must be Greater Than Absents..");
        }


    });
</script>